-- Generated by drizzle-kit as a bare `DROP TABLE`; guarded with IF EXISTS after
-- review (#177). MySQL commits DDL implicitly, so a deploy that dies after this
-- drop but before drizzle records the migration runs it again, and unguarded
-- that retry would fail on every deploy that follows. The guard changes nothing
-- else: the table is gone either way. migrationIntegrity.test.ts enforces it.
DROP TABLE IF EXISTS `shopify_oauth_states`;